#!/usr/bin/env python3
"""
TORAH EXPORT GENERATOR
Creates PDF and HTML book from Torah analysis
"""

import sys
sys.path.insert(0, '/root/hebrew-repo')

from import_torah_complete_v2 import TORAH_COMPLETE
from gematria_calculator import GematriaCalculator

class TorahExporter:
    """Export Torah to various formats"""
    
    def __init__(self):
        self.gem = GematriaCalculator()
    
    def generate_html_book(self, output_file="/root/hebrew-repo/torah_book.html"):
        """Generate HTML book"""
        
        html = """<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Torah Analysis - Complete Study</title>
    <style>
        body { font-family: Georgia, serif; line-height: 1.8; max-width: 800px; margin: 0 auto; padding: 40px 20px; background: #fafafa; }
        h1 { color: #1a365d; border-bottom: 3px solid #2c5282; padding-bottom: 10px; }
        h2 { color: #2c5282; margin-top: 40px; border-left: 4px solid #2c5282; padding-left: 15px; }
        h3 { color: #4a5568; }
        .hebrew { direction: rtl; text-align: right; font-size: 1.3em; background: #edf2f7; padding: 15px; border-radius: 8px; margin: 15px 0; }
        .gematria { background: #ebf8ff; padding: 10px 15px; border-radius: 5px; display: inline-block; margin: 5px; }
        .stats { background: #f0fff4; padding: 20px; border-radius: 8px; margin: 20px 0; }
        .toc { background: #fff; border: 1px solid #e2e8f0; padding: 20px; border-radius: 8px; margin: 20px 0; }
        .toc a { display: block; padding: 5px 0; color: #2c5282; text-decoration: none; }
        .toc a:hover { text-decoration: underline; }
        .verse { margin: 30px 0; padding: 20px; background: white; border-radius: 8px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
        .verse-reference { color: #718096; font-weight: bold; margin-bottom: 10px; }
        .footer { margin-top: 60px; padding-top: 20px; border-top: 1px solid #e2e8f0; color: #718096; text-align: center; }
    </style>
</head>
<body>
    <h1>Torah Analysis - Complete Study</h1>
    <p><strong>A comprehensive analysis of the Five Books of Moses</strong></p>
    <p>Generated by Hebrew Bible Analyzer | Ancient Scripture Reconstruction Project</p>
"""
        
        # Calculate total stats
        total_verses = sum(len(b["key_verses"]) for b in TORAH_COMPLETE.values())
        total_gematria = sum(
            self.gem.calculate(v) 
            for b in TORAH_COMPLETE.values() 
            for v in b["key_verses"].values()
        )
        
        # Statistics section
        html += f"""
    <div class="stats">
        <h2>Project Statistics</h2>
        <p><strong>Total Books:</strong> 5 (Genesis, Exodus, Leviticus, Numbers, Deuteronomy)</p>
        <p><strong>Key Verses Analyzed:</strong> {total_verses}</p>
        <p><strong>Total Gematria:</strong> {total_gematria:,}</p>
        <p><strong>Average Gematria per Verse:</strong> {total_gematria // total_verses:,}</p>
    </div>
"""
        
        # Table of Contents
        html += """
    <div class="toc">
        <h2>Table of Contents</h2>
"""
        for book_name, book_data in TORAH_COMPLETE.items():
            html += f'        <a href="#book-{book_name}">{book_name} ({book_data["hebrew_name"]})</a>\n'
        html += "    </div>\n"
        
        # Each book
        for book_name, book_data in TORAH_COMPLETE.items():
            html += f"""
    <h2 id="book-{book_name}">{book_name}</h2>
    <p><strong>Hebrew Title:</strong> {book_data["hebrew_name"]}</p>
    <p><strong>Chapters:</strong> {book_data["chapters"]} | <strong>Key Verses:</strong> {len(book_data["key_verses"])}</p>
"""
            
            # Verses
            for verse_key, hebrew in sorted(book_data["key_verses"].items()):
                gem = self.gem.calculate(hebrew)
                words = len(hebrew.split())
                verse_ref = f"{verse_key[0]}:{verse_key[1]}"
                
                html += f"""
    <div class="verse">
        <div class="verse-reference">{book_name} {verse_ref}</div>
        <div class="hebrew">{hebrew}</div>
        <div class="gematria">Gematria: {gem}</div>
        <div class="gematria">Words: {words}</div>
    </div>
"""
        
        # Footer
        html += """
    <div class="footer">
        <p>Torah Analysis | Hebrew Bible Analyzer</p>
        <p>Part of the Ancient Scripture Reconstruction Project</p>
        <p><a href="https://github.com/kaibuzz0/HEBREW-REVIVED-">github.com/kaibuzz0/HEBREW-REVIVED-</a></p>
    </div>
</body>
</html>
"""
        
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(html)
        
        print(f"✅ HTML book generated: {output_file}")
        return output_file
    
    def generate_summary(self, output_file="/root/hebrew-repo/torah_summary.md"):
        """Generate Markdown summary"""
        
        md = """# Torah Analysis Summary

## Overview

Complete analysis of the Five Books of Moses (Torah).

## Books Included

"""
        
        for book_name, book_data in TORAH_COMPLETE.items():
            verse_count = len(book_data["key_verses"])
            md += f"### {book_name} ({book_data['hebrew_name']})\n"
            md += f"- **Chapters:** {book_data['chapters']}\n"
            md += f"- **Key Verses Analyzed:** {verse_count}\n\n"
            
            md += "**Key Verses:**\n"
            for verse_key in sorted(book_data["key_verses"].keys())[:5]:
                md += f"- {book_name} {verse_key}\n"
            md += "\n"
        
        # Statistics
        total_verses = sum(len(b["key_verses"]) for b in TORAH_COMPLETE.values())
        total_gematria = sum(
            self.gem.calculate(v) 
            for b in TORAH_COMPLETE.values() 
            for v in b["key_verses"].values()
        )
        
        md += f"""## Statistics

- **Total Books:** 5
- **Total Key Verses:** {total_verses}
- **Total Gematria:** {total_gematria:,}
- **Average Gematria:** {total_gematria // total_verses:,}

## Tools Used

- Gematria Calculator (4 methods)
- 8 Seeds Pattern Analysis
- Resonance Decoder
- Pattern Miner v2.0

## Repository

https://github.com/kaibuzz0/HEBREW-REVIVED-
"""
        
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(md)
        
        print(f"✅ Markdown summary generated: {output_file}")
        return output_file

if __name__ == "__main__":
    exporter = TorahExporter()
    
    print("="*70)
    print("TORAH EXPORT GENERATOR")
    print("="*70)
    
    html_file = exporter.generate_html_book()
    md_file = exporter.generate_summary()
    
    print("\n" + "="*70)
    print("EXPORT COMPLETE")
    print("="*70)
    print(f"\nFiles generated:")
    print(f"  📖 HTML Book: {html_file}")
    print(f"  📝 Markdown: {md_file}")